name: Workflow para Commits
run-name: Workflow para commits sedo executado
on:
  push:
    branches-ignore:
      - main
jobs:
  lint:
    name: Executa ESLint para verificar o estilo de codificação
    runs-on: ubuntu-latest
    steps:
      - name: Faz checkout do repositorio
        uses: actions/checkout@v4

      - name: Instala o Node.js na versão 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instala dependencias necessárias
        run: npm install

      - name: Executa o ESLint
        run: npm run lint

  test:
    name: Executa Testes
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Faz checkout do repositorio
        uses: actions/checkout@v4

      - name: Instala o Node.js na versão 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instala dependencias necessárias
        run: npm install

      - name: Executa os testes
        run: npm run test     
